services:
  backend:
    container_name: backendWPT
    build:
        context: ./
        dockerfile: Containerfile.dev
    volumes:
        - ./:/app
    ports:
      - "8080:8080"

  frontend:
    container_name: frontendWPT
    build:
        context: ../user
        dockerfile: Containerfile.dev
    volumes:
        - ../user/webpartytime:/app/webpartytime
        - /app/webpartytime/node_modules
    ports:
        - "5173:5173"
    depends_on:
      - backend




