CREATE TYPE "party_status" AS ENUM (
  'active',
  'finished',
  'cancelled'
);

CREATE TYPE "asset_type" AS ENUM (
  'image',
  'audio',
  'video'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "scenarios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public" boolean NOT NULL DEFAULT false,
  "creator_id" bigint NOT NULL,
  "title" varchar NOT NULL,
  "description" varchar NOT NULL,
  "script_hash" varchar UNIQUE NOT NULL,
  "cover" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "assets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scenario_id" bigint NOT NULL,
  "type" asset_type NOT NULL,
  "file_hash" varchar NOT NULL,
  "uploaded_by" bigint NOT NULL,
  "uploaded_at" timestamp DEFAULT 'now()'
);

ALTER TABLE "scenarios" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");

ALTER TABLE "assets" ADD FOREIGN KEY ("scenario_id") REFERENCES "scenarios" ("id");

ALTER TABLE "assets" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id");